# Generated by Django 4.0.1 on 2022-03-17 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
