# Generated by Django 4.0.1 on 2022-05-14 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 15, 35, 21, 8384)),
        ),
    ]
