# Generated by Django 4.0.1 on 2022-03-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_note_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='archive',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
