# Generated by Django 4.0.1 on 2022-03-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_note_archive_alter_note_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(blank=True, default='transparent', max_length=50),
        ),
    ]
