# Generated by Django 4.0.1 on 2022-05-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pin',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
