# Generated by Django 4.0.1 on 2022-05-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_remove_note_collaborator_collaborator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborator',
            old_name='note_id',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='collaborator',
            old_name='user_id',
            new_name='user',
        ),
    ]
