# Generated by Django 4.0.1 on 2022-05-16 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_rename_note_id_collaborator_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='note',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='notes.note'),
        ),
    ]
