# Generated by Django 4.0.1 on 2022-05-16 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0019_alter_collaborator_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='collaborator',
            field=models.ManyToManyField(related_name='share_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Collaborator',
        ),
    ]
