# Generated by Django 4.0.1 on 2022-05-17 05:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0020_note_collaborator_delete_collaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='collaborator',
            field=models.ManyToManyField(related_name='collaborator', to=settings.AUTH_USER_MODEL),
        ),
    ]
